services:
  web:
    build: .
    container_name: log_monitoring_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8090:8000"
    depends_on:
      - db
    environment:
      DB_NAME: logdb
      DB_USER: loguser
      DB_PASSWORD: logpass
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:15
    container_name: log_monitoring_db
    environment:
      POSTGRES_DB: logdb
      POSTGRES_USER: loguser
      POSTGRES_PASSWORD: logpass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
